on:
  push:
    branches:
    - main
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - id: check
      uses: shogo82148/actions-check-permissions@v1 

    - name: Check token permissions
      if: steps.check.outputs.permission != 'write'
      run: echo 'invalid permissions'

  prepare:
    name: Create draft release
    runs-on: ubuntu-latest
    
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    
    steps:
    - name: Create draft release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      with:
        draft: true
        prerelease: true
        release_name: Test for ${{ github.run_id }}
  
  build:
    needs: prepare
    
    strategy:
      matrix:
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          binary: tcli.exe
      
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          binary: tcli

    name: Build artifacts for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Restore cache
      uses: Swatinem/rust-cache@v2

    - name: Install cargo-edit
      run: cargo install cargo-edit --locked

    - name: Set Cargo.toml version
      run: cargo set-version ${{ github.ref }}
    
    - name: Build
      run: cargo build --target ${{ matrix.target }} --release

    - name: Upload artifact to draft release
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ needs.prepare.outputs.upload_url }}
        asset_path: ./target/${{ matrix.target }}/release/${{ matrix.binary }}
          